server:
  port: 8002
mybatis:
  type-aliases-package: com.wangxq.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123456


eureka:
  client:
    service-url:
      defaultZone: http://euerka7001.com:7001/eureka/,http://euerka7002.com:7002/eureka/,http://euerka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8002
    hostname: localhost

Info:
  app:
    name: wangxq-springcloud
  company: kevin-white

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  info:
    env:
      enabled: true
#  endpoint:
#    info:
#      env:
#        enabled: true




