server:
  port: 7003
eureka:
  instance:
    hostname: euerka7003.com # Eureka服务端实例名
  client:
    register-with-eureka: false # 是否向Eureka注册中心注册服务（本身）
    fetch-registry: false # false 表示服务本身为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://euerka7002.com:7002/eureka/, http://euerka7001.com:7001/eureka/