server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://euerka7001.com:7001/eureka/,http://euerka7002.com:7002/eureka/,http://euerka7003.com:7003/eureka/
  instance:
    instance-id: zuul-9527
    prefer-ip-address: true

info:
  app.name: wangxq-springcloud
  company: mycompany